"""Card Creator LLM nodes for ComfyUI."""

from .extra_nodes import (
    NODE_CLASS_MAPPINGS as EXTRA_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as EXTRA_NODE_DISPLAY_NAME_MAPPINGS,
)
from .nodes import NODE_CLASS_MAPPINGS as CORE_NODE_CLASS_MAPPINGS
from .nodes import NODE_DISPLAY_NAME_MAPPINGS as CORE_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {**CORE_NODE_CLASS_MAPPINGS, **EXTRA_NODE_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {
    **CORE_NODE_DISPLAY_NAME_MAPPINGS,
    **EXTRA_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
